[batch]
report = "../../reports/batch_baseline.md"
html_report = "../../reports/batch_baseline.html"

[[batch.jobs]]
name = "profile-uniform"
command = "profile"
csv = "../../data/workloads/w_uniform.csv"

[[batch.jobs]]
name = "run-uniform"
command = "run-csv"
csv = "../../data/workloads/w_uniform.csv"
json_summary = "../../results/json/batch_uniform.json"
latency_sample_k = 2000
latency_sample_every = 64
