from __future__ import annotations

from collections.abc import Iterator
from typing import Any

class Draft202012Validator:
    def __init__(self, schema: Any) -> None: ...
    def iter_errors(self, instance: Any) -> Iterator[Any]: ...
    def validate(self, instance: Any) -> None: ...
