name: ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Qt system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            xvfb \
            libgl1 \
            libxkbcommon-x11-0 \
            libglu1-mesa \
            libegl1
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -e '.[dev,gui]'
      - name: Lint
        run: ruff check .
      - name: Type check
        run: mypy .
      - name: Unit tests & coverage
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          xvfb-run -a coverage run -m pytest -q
          coverage report
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: true
      - name: Smoke workload & schema validation
        run: make smoke
